### ISSUE TITLE
Save Only Selected Website URL offline not all URL's.

### ISSUE THREAD

**Issue by pawandeep2155** [rnapier/RNCachingURLProtocol#30]
Currently this library is saving last webpage visited and save it offline and when I load the app again that url is opened. What I want is the user to save the current website html page offline into Sqlite database and load that in a table view which will display all the url's saved.
When the user clicked on the table row the corresponding url should be opened offline in UIWebView.
How can I achieve this. Thank You

**Comment by rnapier** [comment]
Start by making sure you understand how `RNCachiningURLProtocol` works and read over [the original blog post that introduced it](http://robnapier.net/offline-uiwebview-nsurlprotocol). It is mostly just sample code. From there, you'd need to build up a pretty different `NSURLProtocol` to get what you're talking about. You'd probably need to integrate with a `UIWebViewDelegate` to keep track of what original request is making what sub-request. Sounds like an interesting project. It's well beyond that `RNCachingURLProtocol` is trying to solve.

**Comment by pawandeep2155** [comment]
Thank you Rob 👍
