### ISSUE TITLE
2 Questions about this library

### ISSUE THREAD

**Issue by pawandeep2155** [rnapier/RNCachingURLProtocol#31]
2 Questions I want to ask is : 
1. How to specify more than one url for caching
2. Which part of you code is used to get the cache data to display to the UIWebView because I want to use that for saving it to Sqlite database so that I can use that later as an offline view feature.
Thank You

**Comment by rnapier** [comment]
(I know this is 2 years out of date, but it may be helpful to someone in the future.)

1. I'm not certain what you mean; this just caches anything that goes through the `NSURLProtocol`. It can handle any number of connections.
2. In `connection:willSendRequest:redirectResponse:`, see the call to `NSKeyedArchiver` for writing. In `connectionDidFinishLoading:`, see `NSKeyedArchiver` for reading.
