### ISSUE TITLE
WKWebView support

### ISSUE THREAD

**Issue by EvgenyKarkan** [rnapier/RNCachingURLProtocol#32]
Hi @rnapier 
It seems that RNCachingURLProtocol doesn't support WKWebView. 
WKWebView class was introduced in iOS 8 release. 
If you will have some spare time, please take a look at:
- is it possible to cache web pages in WKWebView?
- how to do that?

Best

**Comment by rnapier** [comment]
NSURLProtocols are not honored to WebKit. This approach can't work for that. You'd have to do something much more dramatic (creating a real local proxy and rewriting all the URLs to point back to it, which is massive and fragile).

I'm not aware of any supported techniques for hijacking WebKit in the way you can the URL Loading System. Given that WebKit runs in a separate process, it would be a large feature for them to add (though not impossible). I would keep my eye on the new plugin system to see if hooks are added that might allow this.

**Comment by EvgenyKarkan** [comment]
Hello @rnapier 
I understand, thank you for your time.
Best wishes
